name: Sync to OpenAI Vector Store

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours for stability
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Sync to Vector Store
      uses: shmatt/assistants-vector-store-sync@v1
      with:
        pattern: '**/*.md'
        token: ${{ secrets.OPENAI_API_KEY }}
        key: atticus-knowledge-base